<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VimeoQA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>641fffd5-9770-475d-a162-3278d718d992</testSuiteGuid>
   <testCaseLink>
      <guid>eaad6f8e-7d5d-4d73-a386-845219d429a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/User/UserActions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a151d33-4ea9-4b53-9e9b-ada2906140fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a532158-f79a-4f8d-8507-00b69fbff4ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/commentCheck/commentVerify</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b58bbf1d-1b49-420a-89b7-dc9c84824dca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4076c266-7e9a-4371-98fa-a830603ba951</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec5de8fa-d82b-4a4a-a94a-6a43fd1f5be8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LikesViews/LikeViews</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b6c0da3-41fc-4fb8-8cc0-b57f87e943a0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
