<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Reply_sc-ccSCjj hVgMzj</name>
   <tag></tag>
   <elementGuidId>bd027622-6392-46a5-8c9a-9b0ab32c8e5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='comment_19553614']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comment_19553614 > div.iris_comment > div > div.iris_comment-portrait.undefined > a._1QfB- > img.sc-ccSCjj.hVgMzj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-ccSCjj hVgMzj</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.vimeocdn.com/portrait/defaults-blue_75x75</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://i.vimeocdn.com/portrait/defaults-blue_150x150 2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment_19553614&quot;)/div[@class=&quot;iris_comment&quot;]/div[1]/div[@class=&quot;iris_comment-portrait undefined&quot;]/a[@class=&quot;_1QfB-&quot;]/img[@class=&quot;sc-ccSCjj hVgMzj&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='comment_19553614']/div/div/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://i.vimeocdn.com/portrait/defaults-blue_75x75')])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[10]/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
